elasticsearch:
  restart: always
  image: elasticsearch:5
  ports:
    - 9200:9200
    - 9300:9300
  expose:
    - 9200
  volumes:
#    - ./config:/usr/share/elasticsearch/config
    - ./esdata:/usr/share/elasticsearch/data
    - ./log:/var/log/elasticsearch
  environment:
    ES_JAVA_OPTS: "-Xms2g -Xmx2g"

kibana:
  restart: always
  image: kibana:5
  ports:
    - 5601:5601
  links:
   - elasticsearch:elasticsearch
