version: '3.3'

services:
    web:
        image: httpd:2.4
        ports:
            - "80:80"
        environment:
            JJ_SYS_ENV: "hipicahey"
            JJ_SYS_ENV_NOT: "La la non"
            APACHE_LOGS: "/usr/local/apache2/logs"
        volumes:
            - ./code:/data/www
            - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
        networks:
            - code-network
    php:
        build:
           context: .
           dockerfile: Dockerfile
        image: jmorille/php7-fpm
        volumes:
            - ./code:/data/www
        networks:
            - code-network

networks:
    code-network:
        driver: bridge