version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./code:/data/www
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        build:
           context: .
            dockerfile: Dockerfile
           container_name: jmorille/php:7-fpm
        image: php:7-fpm
        volumes:
            - ./code:/data/www
        networks:
            - code-network

networks:
    code-network:
        driver: bridge