version: '3.3'

services:
    web:
        image: httpd:2.4
        ports:
            - "8080:80"
        volumes:
            - ./code:/usr/local/apache2/htdocs/
            - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
        networks:
            - code-network
    php:
        build:
           context: .
           dockerfile: Dockerfile
        image: jmorille/php7-fpm
        volumes:
            - ./code:/data/www
        networks:
            - code-network

networks:
    code-network:
        driver: bridge