logstash:
  restart: always
  image: jmorille/logstash:latest
  ports:
    - 5044:5044
  expose:
    - 5044
  volumes:
    - ./log:/var/log

beat:
  restart: always
  image: jmorille/beat:latest
  ports:
    - 5601:5601
  links:
   - logstash:logstash
