registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
  expose:
    - 5000
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
    REGISTRY_HTTP_TLS_KEY: /certs/domain.key
    REGISTRY_HTTP_SECRET: asupersecret
    REGISTRY_AUTH: htpasswd
    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
  volumes:
    - ./certs:/certs:ro
    - ./auth:/auth:ro
    - /data/download/docker-registry/lib:/var/lib/registry

registryUI:
  restart: always
  image: konradkleine/docker-registry-frontend:v2
  ports:
    - 80:80
    - 443:443
  links:
   - registry:registry
  environment:
    ENV_DOCKER_REGISTRY_HOST: registry
    ENV_DOCKER_REGISTRY_PORT: 5000
    ENV_DOCKER_REGISTRY_USE_SSL: 1
    ENV_USE_SSL: "yes"
  volumes:
    - ./certs/domain.crt:/etc/apache2/server.crt:ro
    - ./certs/domain.key:/etc/apache2/server.key:ro
