registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
  expose:
    - 5000
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
    REGISTRY_HTTP_TLS_KEY: /certs/domain.key
    REGISTRY_AUTH: htpasswd
    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
  volumes:
    - $PWD/certs:/certs
    - $PWD/auth:/auth
    - /data/download/docker-registry/lib:/var/lib/registry

registryUI:
  restart: always
  image: konradkleine/docker-registry-frontend:v2
  ports:
    - 8080:80
    - 443:443
  links:
   - registry:registry
  environment:
    ENV_DOCKER_REGISTRY_HOST: registry
    ENV_DOCKER_REGISTRY_PORT: 5000
    ENV_DOCKER_REGISTRY_USE_SSL: 1
  volumes:
    - $PWD/certs/domain.crt:/etc/apache2/server.crt:ro
    - $PWD/certs/domain.key:/etc/apache2/server.key:ro
