web:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: 'thor'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://thor:9090'
      gitlab_rails['gitlab_shell_ssh_port'] = 2224
      nginx['redirect_http_to_https'] = true
      nginx['ssl_certificate'] = "/etc/gitlab/ssl/domain.crt"
      nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/domain.key"
  ports:
    - '9090:9090'
    - '2224:22'
  volumes:
    - './srv/gitlab/config:/etc/gitlab'
    - './srv/gitlab/logs:/var/log/gitlab'
    - './srv/gitlab/data:/var/opt/gitlab'
