web:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: 'thor'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://thor:9090'
      gitlab_rails['gitlab_shell_ssh_port'] = 2224
      # Certificate
      nginx['redirect_http_to_https'] = true
      nginx['ssl_certificate'] = "/etc/gitlab/certs/domain.crt"
      nginx['ssl_certificate_key'] = "/etc/gitlab/certs/domain.key"
      # SMTP Gmail
      gitlab_rails['smtp_enable'] = false
      gitlab_rails['smtp_address'] = "smtp.gmail.com"
      gitlab_rails['smtp_port'] = 587
      gitlab_rails['smtp_user_name'] = "my.email@gmail.com"
      gitlab_rails['smtp_password'] = "my-gmail-password"
      gitlab_rails['smtp_domain'] = "smtp.gmail.com"
      gitlab_rails['smtp_authentication'] = "login"
      gitlab_rails['smtp_enable_starttls_auto'] = true
      gitlab_rails['smtp_tls'] = false
      gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
  ports:
    - '9091:9090'
    - '2224:22'
  volumes:
    - './certs:/etc/gitlab/certs'
    - './config:/etc/gitlab'
    - './logs:/var/log/gitlab'
    - './data:/var/opt/gitlab'
