from elasticsearch:5

RUN usermod -u 1000 elasticsearch

# Plugins : https://www.elastic.co/guide/en/elasticsearch/plugins/5.x/installation.html

# RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install jettro/elasticsearch-gui

RUN elasticsearch-plugin list
